name: Python CI
on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref}}
env:
  POETRY_VERSION: 1.8.3
jobs:
  python-ci:
    env:
      DEBUG: 1
    if: github.event.pull_request.draft == false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: "python:\n  - 'graphrag/**/*'\n  - 'poetry.lock'\n  - 'pyproject.toml'\n\
            \  - '**/*.py'\n  - '**/*.toml'\n  - '**/*.ipynb'\n  - '.github/workflows/python*.yml'\n\
            \  - 'tests/**/*'\n"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: $POETRY_VERSION
      - name: Install dependencies
        run: 'poetry self add setuptools wheel

          poetry run python -m pip install gensim

          poetry install

          '
        shell: bash
      - id: measurement-6
        name: Record Measurement After Install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install dependencies
          task: get-measurement
      - name: Check
        run: 'poetry run poe check

          '
      - id: measurement-8
        name: Record Measurement After Check
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Check
          task: get-measurement
      - name: Build
        run: 'poetry build

          '
      - id: measurement-10
        name: Record Measurement After Build
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Build
          task: get-measurement
      - name: Unit Test
        run: 'poetry run poe test_unit

          '
      - id: measurement-12
        name: Record Measurement After Unit Test
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Unit Test
          task: get-measurement
      - name: Verb Test
        run: poetry run poe test_verbs
      - id: measurement-14
        name: Record Measurement After Verb Test
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Verb Test
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        python-version:
          - '3.10'
          - '3.11'
permissions:
  contents: read
  pull-requests: read
